export const noir = {
  id: 'noir',
  label: 'Noir / Blade Runner',
  tables: {
    firstNames: ['Otto', 'Mara', 'Cyrus', 'Dita', 'Lev', 'Priya', 'Sol', 'Neena', 'Bram', 'Vesna'],
    surnames: ['Brandt', 'Okoye', 'Vance', 'Marlow', 'Sato', 'Kessler', 'Reyes', 'Dahl', 'Cole', 'Nyx'],
    looks: [
      'Heavyset, oil-stained cuffs, a rosary they keep touching',
      'Rail-thin, chrome tooth, coat two sizes too big',
      'Ex-military posture gone to seed, nicotine-yellow fingers',
      'Immaculate suit, one cracked lens in their glasses',
      'Burn scar down one wrist, always half in shadow',
      'Too-bright dye job, roots showing, tired eyes',
      'Synthetic-smooth skin that never quite reads as alive',
      'Missing a fingertip, hides the hand when they notice you looking',
    ],
    manners: [
      'Over-friendly, laughs a beat too late',
      'Answers questions with questions',
      'Won\'t sit with their back to the door',
      'Counts their words like they cost money',
      'Flatters you, then watches to see if it landed',
      'Keeps checking a watch that isn\'t there',
      'Talks fast when lying, slow when it\'s worse',
    ],
    wants: [
      'The debt gone before their shift ends',
      'A name - someone else to take the fall',
      'Out of the city on the last transport',
      'To be believed, just once',
      'The photograph back before anyone else sees it',
      'Protection they\'re too proud to ask for',
    ],
    secrets: [
      'Signed off the container they never inspected',
      'Is already talking to the other side',
      'The person you\'re looking for is family',
      'Sold the access codes months ago',
      'Isn\'t who their papers say they are',
      'Watched it happen and did nothing',
    ],
    voices: [
      'Says "you understand me?" after everything',
      'Never finishes the last word of a sentence',
      'Drops into a second language when rattled',
      'Calls everyone "friend" like a threat',
      'Over-enunciates, like reciting',
      'Laughs at their own lines before they land',
    ],
  },
};
